default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: typing_app_development

test:
  <<: *default
  database: typing_app_test

production:
  <<: *default
  database: typing_app_production
  username: typing-app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
